# Generated by Django 3.2.7 on 2022-04-12 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemento',
            name='gestion',
        ),
        migrations.RemoveField(
            model_name='elemento',
            name='gestion_planificada',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='area',
        ),
        migrations.RemoveField(
            model_name='gestionnoplanificada',
            name='gestor',
        ),
        migrations.RemoveField(
            model_name='gestionnoplanificada',
            name='om',
        ),
        migrations.RemoveField(
            model_name='gestionnoplanificada',
            name='plataforma',
        ),
        migrations.RemoveField(
            model_name='gestionplanificada',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='gestionplanificada',
            name='gerente',
        ),
        migrations.RemoveField(
            model_name='gestionplanificada',
            name='gestor',
        ),
        migrations.RemoveField(
            model_name='noplanificada',
            name='promotor',
        ),
        migrations.DeleteModel(
            name='Planificada',
        ),
        migrations.RemoveField(
            model_name='plataforma',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='promotor',
            name='gerente',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Elemento',
        ),
        migrations.DeleteModel(
            name='Gerente',
        ),
        migrations.DeleteModel(
            name='GestionNoPlanificada',
        ),
        migrations.DeleteModel(
            name='GestionPlanificada',
        ),
        migrations.DeleteModel(
            name='Gestor',
        ),
        migrations.DeleteModel(
            name='NoPlanificada',
        ),
        migrations.DeleteModel(
            name='Plataforma',
        ),
        migrations.DeleteModel(
            name='Promotor',
        ),
    ]
