# Generated by Django 3.2.7 on 2022-03-15 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0002_alter_elemento_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionPlanificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('om', models.CharField(blank=True, max_length=200, null=True, verbose_name='OM')),
                ('titulo', models.CharField(blank=True, max_length=2000, null=True, verbose_name='TITULO')),
                ('descripcion', models.TextField(blank=True, max_length=2000, null=True, verbose_name='DESCRIPCIÓN')),
                ('afectacion_b2b_b2c', models.CharField(blank=True, choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('N/A', 'N/A')], max_length=200, null=True, verbose_name='AFECTACIÓN (B2B o B2C)')),
                ('criticidad', models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Critical', 'Critical')], max_length=200, null=True, verbose_name='CRITICIDAD DEL CAMBIO')),
                ('impacto', models.CharField(blank=True, choices=[('Afectación', 'Afectación'), ('Riesgo', 'Riesgo'), ('N/A', 'N/A')], max_length=200, null=True, verbose_name='IMPACTO')),
                ('tiempo_ejecucion', models.DurationField(blank=True, max_length=200, null=True, verbose_name='TIEMPO DE EJECUCIÓN')),
                ('tiempo_rollback', models.DurationField(blank=True, max_length=200, null=True, verbose_name='TIEMPO DE ROLLBACK')),
                ('tiempo_afectacion', models.DurationField(blank=True, max_length=200, null=True, verbose_name='TIEMPO DE AFECTACION')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='FECHA INICIO')),
                ('fecha_fin', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='FECHA FIN')),
                ('afectacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='AFECTACIÓN')),
                ('horario', models.CharField(blank=True, max_length=200, null=True, verbose_name='HORARIO DE AFECTACIÓN')),
                ('area', models.CharField(blank=True, max_length=200, null=True, verbose_name='AREA')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='COMENTARIOS EXTRAS')),
                ('comentarios_fechas', models.TextField(blank=True, null=True, verbose_name='COMENTARIOS SOBRE FECHAS')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='MOTIVO DEL RECHAZO')),
                ('aprobada_por_area', models.BooleanField(blank=True, default=False, null=True, verbose_name='APROBADA POR EL AREA')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_categoria', to='cambio.categoria', verbose_name='Categoria')),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_gerente_red', to='cambio.gerente', verbose_name='Gerente')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_gestor', to='cambio.categoria', verbose_name='Gestor')),
            ],
            options={
                'verbose_name': 'Gestión Planificada',
                'verbose_name_plural': 'Gestión de las Planificadas',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Planificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Usuario Reviso')),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Solicitud')),
                ('tarea', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Tarea')),
                ('titulo_tarea', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Titulo Tarea')),
                ('tipo_elemento', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Tipo de Elemento')),
                ('elemento', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Elemento')),
                ('tipo_trabajo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Tipo de Trabajo')),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Ejecución')),
                ('area_asignada', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Area Asignada')),
                ('extraccion', models.BooleanField(blank=True, default=False, null=True, verbose_name='Se hizo la Extracción?')),
                ('area', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Area')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Cambio Planificado',
                'verbose_name_plural': 'Cambios  Planificados',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='elemento',
            name='actividad',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Actividad'),
        ),
        migrations.AddField(
            model_name='gestionnoplanificada',
            name='comentarios_fechas',
            field=models.TextField(blank=True, null=True, verbose_name='COMENTARIOS SOBRE FECHAS'),
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.AddField(
            model_name='elemento',
            name='gestion_planificada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_elemento_planificada', to='cambio.gestionplanificada', verbose_name='OT Planificada'),
        ),
    ]
