# Generated by Django 3.2.7 on 2022-04-25 03:07

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0003_area_categoria_elemento_gerente_gestionnoplanificada_gestionplanificada_gestor_noplanificada_planifi'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionnoplanificada',
            name='estatus',
            field=models.CharField(blank=True, choices=[('APROBADA', 'APROBADA'), ('CANCELADA', 'CANCELADA'), ('EN REVISION', 'EN REVISION')], default='REVISION', max_length=1000, null=True, verbose_name='ESTATUS'),
        ),
        migrations.AddField(
            model_name='gestionplanificada',
            name='autor',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='AUTOR'),
        ),
        migrations.AddField(
            model_name='gestionplanificada',
            name='color_borde',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='Color del Borde'),
        ),
        migrations.AddField(
            model_name='gestionplanificada',
            name='color_evento',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='Color de Fondo'),
        ),
        migrations.AddField(
            model_name='gestionplanificada',
            name='color_text',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='Color del Texto'),
        ),
        migrations.AddField(
            model_name='gestionplanificada',
            name='estatus',
            field=models.CharField(blank=True, choices=[('APROBADA', 'APROBADA'), ('CANCELADA', 'CANCELADA'), ('EN REVISION', 'EN REVISION')], default='REVISION', max_length=1000, null=True, verbose_name='ESTATUS'),
        ),
        migrations.AddField(
            model_name='gestionplanificada',
            name='fecha_fin_afectacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FECHA FIN DE AFECTACION'),
        ),
        migrations.AddField(
            model_name='gestionplanificada',
            name='fecha_inicio_afectacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FECHA INICIO DE AFECTACION'),
        ),
        migrations.AddField(
            model_name='planificada',
            name='firma',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='planificada',
            name='reprogramada',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Reprogramada?'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nombre del Area'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nombre de Categoria'),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='last_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='mail',
            field=models.EmailField(blank=True, max_length=1000, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='phone',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='gestionnoplanificada',
            name='afectacion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='AFECTACIÓN'),
        ),
        migrations.AlterField(
            model_name='gestionnoplanificada',
            name='afectacion_b2b_b2c',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('N/A', 'N/A')], max_length=1000, null=True, verbose_name='AFECTACIÓN (B2B o B2C)'),
        ),
        migrations.AlterField(
            model_name='gestionnoplanificada',
            name='area',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='AREA'),
        ),
        migrations.AlterField(
            model_name='gestionnoplanificada',
            name='criticidad',
            field=models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Critical', 'Critical')], max_length=1000, null=True, verbose_name='CRITICIDAD DEL CAMBIO'),
        ),
        migrations.AlterField(
            model_name='gestionnoplanificada',
            name='horario_entre_afectacion',
            field=models.DateTimeField(blank=True, max_length=1000, null=True, verbose_name='HORARIO FIN AFECTACION'),
        ),
        migrations.AlterField(
            model_name='gestionnoplanificada',
            name='impacto',
            field=models.CharField(blank=True, choices=[('Afectación', 'Afectación'), ('Riesgo', 'Riesgo'), ('N/A', 'N/A')], max_length=1000, null=True, verbose_name='IMPACTO'),
        ),
        migrations.AlterField(
            model_name='gestionnoplanificada',
            name='tiempo_afectacion',
            field=models.DurationField(blank=True, max_length=1000, null=True, verbose_name='TIEMPO DE AFECTACION'),
        ),
        migrations.AlterField(
            model_name='gestionnoplanificada',
            name='tiempo_ejecucion',
            field=models.DurationField(blank=True, max_length=1000, null=True, verbose_name='TIEMPO DE EJECUCIÓN'),
        ),
        migrations.AlterField(
            model_name='gestionnoplanificada',
            name='tiempo_rollback',
            field=models.DurationField(blank=True, max_length=1000, null=True, verbose_name='TIEMPO DE ROLLBACK'),
        ),
        migrations.AlterField(
            model_name='gestionplanificada',
            name='afectacion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='AFECTACIÓN'),
        ),
        migrations.AlterField(
            model_name='gestionplanificada',
            name='afectacion_b2b_b2c',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('N/A', 'N/A')], max_length=1000, null=True, verbose_name='AFECTACIÓN (B2B o B2C)'),
        ),
        migrations.AlterField(
            model_name='gestionplanificada',
            name='area',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='AREA'),
        ),
        migrations.AlterField(
            model_name='gestionplanificada',
            name='criticidad',
            field=models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Critical', 'Critical')], max_length=1000, null=True, verbose_name='CRITICIDAD DEL CAMBIO'),
        ),
        migrations.AlterField(
            model_name='gestionplanificada',
            name='gerente',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Gerente'),
        ),
        migrations.AlterField(
            model_name='gestionplanificada',
            name='gestor',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='GESTOR'),
        ),
        migrations.AlterField(
            model_name='gestionplanificada',
            name='horario',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='HORARIO DE AFECTACIÓN'),
        ),
        migrations.AlterField(
            model_name='gestionplanificada',
            name='impacto',
            field=models.CharField(blank=True, choices=[('Afectación', 'Afectación'), ('Riesgo', 'Riesgo'), ('N/A', 'N/A')], max_length=1000, null=True, verbose_name='IMPACTO'),
        ),
        migrations.AlterField(
            model_name='gestionplanificada',
            name='om',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='OM'),
        ),
        migrations.AlterField(
            model_name='gestionplanificada',
            name='tiempo_afectacion',
            field=models.DurationField(blank=True, max_length=1000, null=True, verbose_name='TIEMPO DE AFECTACION'),
        ),
        migrations.AlterField(
            model_name='gestionplanificada',
            name='tiempo_ejecucion',
            field=models.DurationField(blank=True, max_length=1000, null=True, verbose_name='TIEMPO DE EJECUCIÓN'),
        ),
        migrations.AlterField(
            model_name='gestionplanificada',
            name='tiempo_rollback',
            field=models.DurationField(blank=True, max_length=1000, null=True, verbose_name='TIEMPO DE ROLLBACK'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='last_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='mail',
            field=models.EmailField(blank=True, max_length=1000, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='phone',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='noplanificada',
            name='horario_afectacion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='horario de Afectación'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nombre de Categoria'),
        ),
        migrations.AlterField(
            model_name='promotor',
            name='last_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='promotor',
            name='mail',
            field=models.EmailField(blank=True, max_length=1000, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='promotor',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='promotor',
            name='phone',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Teléfono'),
        ),
    ]
