# Generated by Django 3.2.7 on 2022-04-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0004_auto_20220424_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nombre del Elemento'),
        ),
    ]
