# Generated by Django 3.2.7 on 2021-10-15 19:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ENTREGADO', 'ENTREGADO'), ('RECHAZADO', 'RECHAZADO'), ('ACEPTADO', 'ACEPTADO')], max_length=45, verbose_name='Nombre')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('motivo', models.CharField(blank=True, choices=[('FALTA DE INFORMACION', 'FALTA DE INFORMACION'), ('ERROR EN LA DOCUMENTACION', 'ERROR EN LA DOCUMENTACION')], max_length=45, null=True, verbose_name='Motivo')),
                ('adicionales', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Comentarios Adicionales')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Estatus',
                'verbose_name_plural': 'Estatus',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Ingeniero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ingeniero que Entrega')),
                ('mail', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Ingeniero',
                'verbose_name_plural': 'Ingenieros',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Troncal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Troncal IPO')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Troncal',
                'verbose_name_plural': 'Troncales',
                'ordering': ('created',),
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('created',), 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categoria'},
        ),
        migrations.RemoveField(
            model_name='performance',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='performance',
            name='ab',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ancho de Banda'),
        ),
        migrations.AddField(
            model_name='performance',
            name='identificador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OE-OI'),
        ),
        migrations.AddField(
            model_name='performance',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='performance',
            name='regio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo Regio'),
        ),
        migrations.AddField(
            model_name='performance',
            name='region',
            field=models.CharField(blank=True, choices=[('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3'), ('R4', 'R4'), ('R5', 'R5'), ('R6', 'R6'), ('R7', 'R7'), ('R8', 'R8'), ('R9', 'R9'), ('TGS', 'TGS')], max_length=45, null=True, verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='performance',
            name='saltos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Saltos'),
        ),
        migrations.AddField(
            model_name='performance',
            name='sucursal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='performance',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Principal', 'Principal'), ('Backup', 'Backup')], max_length=45, null=True, verbose_name='Tipo Enlace'),
        ),
        migrations.AddField(
            model_name='performance',
            name='unico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID UNICO'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la SubCategoria'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_categoria', to='performance.categoria', verbose_name='Categoria'),
        ),
        migrations.DeleteModel(
            name='SubCategoria',
        ),
        migrations.AddField(
            model_name='estatus',
            name='ingeniero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_ingeniero', to='performance.ingeniero', verbose_name='Nombre del Ingeniero'),
        ),
        migrations.AddField(
            model_name='estatus',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_performance', to='performance.performance', verbose_name='Escoja la MT'),
        ),
        migrations.AddField(
            model_name='performance',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_servicio', to='performance.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='performance',
            name='troncal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_troncal', to='performance.troncal', verbose_name='Troncal IPO'),
        ),
    ]
