# Generated by Django 3.2.7 on 2022-01-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_alter_estatus_adicionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatus',
            name='motivo',
            field=models.CharField(blank=True, choices=[('FALTA DE INFORMACION', 'FALTA DE INFORMACION'), ('ERROR EN LA DOCUMENTACION', 'ERROR EN LA DOCUMENTACION'), ('DEPURAR ELEMENTOS', 'DEPURAR ELEMENTOS'), ('PROBLEMAS EN EL SERVICIO', 'PROBLEMAS EN EL SERVICIO')], max_length=45, null=True, verbose_name='Motivo'),
        ),
    ]
