# Generated by Django 3.2.7 on 2022-03-18 22:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_alter_estatus_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatus',
            name='errores',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Errores'),
        ),
        migrations.AddField(
            model_name='estatus',
            name='primera',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Primera Revisión?'),
        ),
        migrations.AddField(
            model_name='estatus',
            name='tiempo_respuesta',
            field=models.DurationField(blank=True, null=True, verbose_name='Tiempo de Respuesta'),
        ),
        migrations.AlterField(
            model_name='estatus',
            name='adicionales',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Comentarios Adicionales'),
        ),
    ]
