# Generated by Django 3.2.7 on 2022-03-24 00:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_auto_20220318_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatus',
            name='adicionales',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Comentarios Adicionales'),
        ),
    ]
