# Generated by Django 3.2.7 on 2022-01-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healtcheaks', '0003_auto_20220104_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatusinteratt',
            name='macno_centro_bundle_ether_300_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MACNO CENTRO  BUNDLE-ETHER 300'),
        ),
    ]
