# Generated by Django 3.2.7 on 2022-01-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healtcheaks', '0004_estatusinteratt_macno_centro_bundle_ether_300_comentarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComentariosInterATT',
        ),
        migrations.AlterModelOptions(
            name='estatusinteratt',
            options={'verbose_name': 'Interconexión ATT', 'verbose_name_plural': 'Interconexión ATT'},
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='can_rsocun01_trunk_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CAN_RSOCUN01-TRUNK'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='can_rsocun01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CAN_RSOCUN01-VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='hmty0237_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='HMTY0237 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='mer_msomer01_trunk_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MER_MSOMER01-TRUNK'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='mer_msomer02_trunk_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MER_MSOMER02-TRUNK'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='mer_msomer02_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MER_MSOMER02-VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='mexzum8148_bundle_ether_500_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MEXZUM8148 BUNDLE-ETHER 500'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='mexzum8148_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MEXZUM8148 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='mor_miczam1225_trunk_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MOR_MICZAM1225-TRUNK'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='mor_miczam1225_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MOR_MICZAM1225-VLAN´S  '),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msocab01_port_channel_300_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOCAB01 PORT-CHANNEL 300'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msocab01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOCAB01 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msocjup01_bundle_ether_300_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOCJUP01 BUNDLE-ETHER 300'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msocjup01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOCJUP01 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msogdl01_bundle_ether_300_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOGDL01 BUNDLE-ETHER 300'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msogdl01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOGDL01 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msomex01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOMEX01 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msomex02_bundle_ether_500_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOMEX02 BUNDLE-ETHER 500'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msomex02_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOMEX02 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msomex03_bundle_ether_500_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOMEX03 BUNDLE-ETHER 500'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msomex03_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOMEX03 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msomex04_bundle_ether_400_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOMEX04 BUNDLE-ETHER 400'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msomex04_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOMEX04 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msomty01_bundle_ether_300_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOMTY01 BUNDLE-ETHER 300'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msomty01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOMTY01 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msopue01_bundle_ether_300_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOPUE01  BUNDLE-ETHER 300'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msopue01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOPUE01  VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msotjp01_bundle_ether_300_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOTJP01 BUNDLE-ETHER 300'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msotjp01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOTJP01 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msotol01_ether_trunk_100_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOTOL01 ETHER-TRUNK 100'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='msotol01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MSOTOL01 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='nld_rsonld01_bundle_ether_300_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NLD_RSONLD01 BUNDLE-ETHER 300'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='nld_rsonld01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NLD_RSONLD01 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='rey_rsorey01_bundle_ether_300_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='REY_RSOREY01 BUNDLE-ETHER 300'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='rey_rsorey01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='REY_RSOREY01 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='rsochi01_bundle_ether_300_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='RSOCHI01 BUNDLE-ETHER 300'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='rsochi01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='RSOCHI01 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='rsopue01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='RSOPUE01  VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='rsotol01_ether_trunk_100_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='RSOTOL01 ETHER-TRUNK 100'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='rsotol01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='RSOTOL01 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='tam_htpc0030_bundle_ether_300_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TAM_HTPC0030 BUNDLE-ETHER 300'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='tam_htpc0030_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TAM_HTPC0030  VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='tam_rsotpoc01_bundle_ether_300_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TAM_RSOTPOC01 BUNDLE-ETHER 300'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='tam_rsotpoc01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TAM_RSOTPOC01 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='tap_chptap0102_port_channel_300_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TAP_CHPTAP0102  PORT-CHANNEL 300'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='tep_chptap0102_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TEP_CHPTAP0102-VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='tor_250_bundle_ether_300_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TOR-250 BUNDLE-ETHER 300'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='tor_250_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TOR-250 VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='uru_micrys1186_trunk_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URU_MICRYS1186-TRUNK'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='uru_micrys1186_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URU_MICRYS1186-VLAN´S  '),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='uru_micsae1190_trunk_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URU_MICSAE1190-TRUNK'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='uru_micsae119_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URU_MICSAE119-VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='uru_micuru1210_port_channel_300_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URU_MICURU1210  PORT-CHANNEL 300'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='uru_micuru1210_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URU_MICURU1210-VLAN´S'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='vhe_msovhe01_trunk_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='VHE_MSOVHE01-TRUNK'),
        ),
        migrations.AddField(
            model_name='estatusinteratt',
            name='vhe_msovhe01_vlan_comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='VHE_MSOVHE01-VLAN´S  '),
        ),
    ]
