# Generated by Django 3.2.7 on 2022-01-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healtcheaks', '0005_auto_20220104_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatusinteratt',
            options={'verbose_name': 'Interconfiguración ATT', 'verbose_name_plural': 'Interconfiguración ATT'},
        ),
    ]
