# Generated by Django 3.2.7 on 2021-11-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=0, verbose_name='Numero del Ticket')),
                ('fase', models.CharField(max_length=200, verbose_name='Fase Migración')),
                ('regio', models.CharField(max_length=200, verbose_name='Regio')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('sucursal', models.CharField(max_length=200, verbose_name='Sucursal')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de la Ventana')),
                ('horario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Horario')),
                ('om', models.CharField(blank=True, max_length=200, null=True, verbose_name='Orden Maestra')),
                ('vlan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vlan´s')),
                ('modelo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Modelo Cpe')),
                ('serie_cpe', models.CharField(blank=True, max_length=200, null=True, verbose_name='Serie Cpe')),
                ('idcs', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Idcs')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Notificación Dalia',
                'verbose_name_plural': 'Notificaciones proyecto Dalia',
                'ordering': ('created',),
            },
        ),
    ]
