# Generated by Django 3.2.7 on 2021-10-10 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Estado del Folio',
                'verbose_name_plural': 'Estados de los Folios',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Etapa  del Proyecto',
                'verbose_name_plural': 'Etapas  del Proyecto',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='GestionProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, verbose_name='Número de FG')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo de FG')),
                ('registro', models.BooleanField(blank=True, default=False, null=True, verbose_name='Fue en Tiempo el Registro?')),
                ('proactivo', models.BooleanField(blank=True, default=False, null=True, verbose_name='Proactivo?')),
                ('postmortem', models.BooleanField(blank=True, default=False, null=True, verbose_name='Postmortem?')),
                ('postmortem_acuse', models.BooleanField(blank=True, default=False, null=True, verbose_name='Se entrego en tiempo?')),
                ('minutas', models.BooleanField(blank=True, default=False, null=True, verbose_name='Se entrego minutas?')),
                ('problema', models.BooleanField(blank=True, default=False, null=True, verbose_name='Error en la Gestión?')),
                ('calidad', models.BooleanField(blank=True, default=True, null=True, verbose_name='Calidad de Cierre?')),
                ('calidad_inventario', models.BooleanField(blank=True, default=True, null=True, verbose_name='Calidad de Inventario?')),
                ('kedb', models.BooleanField(blank=True, default=False, null=True, verbose_name='Reporte kedb?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_estados', to='kpi.estado', verbose_name='Estado')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_etapas', to='kpi.estado', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Gestor de Problema',
                'verbose_name_plural': 'Gestores de Problemas',
                'ordering': ('created',),
            },
        ),
    ]
