# Generated by Django 3.2.7 on 2021-09-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='name',
        ),
        migrations.AddField(
            model_name='gestion',
            name='impacto',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Impacto al Negocio'),
        ),
    ]
