# Generated by Django 3.2.7 on 2021-09-28 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0002_auto_20210927_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='tecnologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_tecnologia_soc', to='problema.tecnologiacatalogo', verbose_name='Tecnología Soc'),
        ),
        migrations.AlterField(
            model_name='soportetemm',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido del Soporte'),
        ),
        migrations.AlterField(
            model_name='soportetemm',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email del Soporte'),
        ),
        migrations.AlterField(
            model_name='soportetemm',
            name='mrn',
            field=models.CharField(max_length=100, verbose_name='MRN del Soporte'),
        ),
        migrations.AlterField(
            model_name='soportetemm',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Sorpote'),
        ),
    ]
