# Generated by Django 3.2.7 on 2021-09-28 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0003_auto_20210928_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='entregable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_entregable', to='problema.entregable', verbose_name='Entregable'),
        ),
    ]
