# Generated by Django 3.2.7 on 2021-10-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0003_alter_gestion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='id_proyecto',
            field=models.PositiveIntegerField(default=0, verbose_name='ID de grupo'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='ot',
            field=models.ManyToManyField(blank=True, related_name='get_ots', to='problema.Ot', verbose_name='Orden de Trabajo'),
        ),
    ]
