# Generated by Django 3.2.7 on 2021-10-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0004_auto_20211015_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='estatus',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='id_grupo',
            field=models.PositiveIntegerField(default=0, verbose_name='ID del Workflow'),
        ),
    ]
