# Generated by Django 3.2.7 on 2021-09-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0004_grupo_entregable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='entregable',
        ),
        migrations.AddField(
            model_name='entregable',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_grupo', to='problema.grupo', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Entregable'),
        ),
    ]
