# Generated by Django 3.2.7 on 2021-09-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0005_auto_20210928_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='grupo',
            field=models.ManyToManyField(related_name='get_elementos', to='problema.Grupo', verbose_name='Grupos'),
        ),
    ]
