# Generated by Django 3.2.7 on 2021-11-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0006_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='comentarios_vista',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Comentarios vista'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='cumplimiento',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cumplimiento'),
        ),
    ]
