# Generated by Django 3.2.7 on 2021-11-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0007_auto_20211118_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='backlog',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cumplimiento'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='comentarios_vista',
            field=models.TextField(default='', verbose_name='Comentarios generales'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='cumplimiento',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cumplimiento para vista'),
        ),
    ]
