# Generated by Django 3.2.7 on 2021-11-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0010_auto_20211118_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='comentarios_vista',
            field=models.TextField(default='', verbose_name='Comentarios vista'),
        ),
    ]
