# Generated by Django 3.2.7 on 2021-11-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0011_alter_gestion_comentarios_vista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='backlog',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Backlog'),
        ),
    ]
