# Generated by Django 3.2.7 on 2021-11-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0013_auto_20211129_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='otros',
            field=models.CharField(blank=True, default='', help_text="Solo en caso de escoger 'Otros'", max_length=75, null=True, verbose_name='Especificar nombre'),
        ),
    ]
