# Generated by Django 3.2.7 on 2021-11-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0014_alter_entregable_otros'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='fecha_alta_workflow',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha alta en Workflow'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='fecha_ola',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio de la ola'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='fecha_pp',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha puesta en producción'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='ola',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='OLA'),
        ),
    ]
