# Generated by Django 3.2.7 on 2021-12-10 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0015_auto_20211130_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('asunto', models.CharField(max_length=130, verbose_name='Asunto')),
                ('remitente', models.CharField(max_length=130, verbose_name='Remitente')),
                ('anexo1', models.CharField(max_length=130, verbose_name='Anexo1')),
                ('anexo2', models.PositiveIntegerField(verbose_name='Anexo2')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problema.gestion', verbose_name='Proyecto')),
            ],
        ),
    ]
