# Generated by Django 3.2.7 on 2022-01-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0016_correoproyectos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correoproyectos',
            options={'verbose_name': 'Correo proyectos', 'verbose_name_plural': 'Correo proyectos'},
        ),
    ]
