# Generated by Django 3.2.7 on 2022-03-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problema', '0019_gestion_palabra_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='correo_seguimiento',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Correo de segumiento'),
        ),
    ]
